# https://github.com/shiftkey/desktop/releases
- name: Install github-desktop
  apt:
    deb: https://github.com/shiftkey/desktop/releases/download/release-2.9.0-linux2/GitHubDesktop-linux-2.9.0-linux2.deb