# https://github.com/shiftkey/desktop/releases
- name: Install github-desktop
  apt:
    deb: https://github.com/shiftkey/desktop/releases/download/release-2.8.3-linux1/GitHubDesktop-linux-2.8.3-linux1.deb