- name: Run playbook for general environment
  hosts: localhost
  become: yes
  roles:
    - xfce-config
    - display
    - sound
    - switcheroo
    - openvpn
    - group-wheel
    # install docker before creating users because 'docker' group 
    # doesn't exist before we install docker
    - docker
    - user
    - discord
    - steam
    - slack
    - clickup
    - chromium
    - typora
    - notepadqq
    - apt-upgrade