# https://support.typora.io/Typora-on-Linux/
- name: Add Typora signing key
  ansible.builtin.apt_key:
    url: https://typora.io/linux/public-key.asc
    state: present

- name: Add Typora repository
  ansible.builtin.apt_repository:
    repo: deb https://typora.io/linux ./
    state: present
    filename: typora

- name: Install Typora
  apt:
    name: typora
    update_cache: yes
    state: present