# https://askubuntu.com/questions/1230833/annoying-click-popping-sound-on-ubuntu-20-04
- name: Disable sound card power-saving
  ansible.builtin.shell: echo "0" | sudo tee /sys/module/snd_hda_intel/parameters/power_save

- name: Disable sound card power-save controller
  ansible.builtin.shell: echo "0" | sudo tee /sys/module/snd_hda_intel/parameters/power_save_controller

- name: Persist power-saving changes
  ansible.builtin.shell: |
    echo "options snd_hda_intel power_save=0" | sudo tee /etc/modprobe.d/audio_disable_powersave.conf
    echo "options snd_hda_intel power_save_controller=N" | sudo tee -a /etc/modprobe.d/audio_disable_powersave.conf